spring:
  application:
    name: "ms-challenge-persons"
  devtools:
    restart:
      enabled: false
    add-properties: false
  jpa:
    hibernate:
      ddl-auto: "validate"
    databasePlatform: "org.hibernate.dialect.H2Dialect"
  datasource:
    url: "jdbc:postgresql://localhost:5432/person"
    username: "postgres"
    password: "person2023"
    driver-class-name: "org.postgresql.Driver"



  r2dbc:
    enabled: true


