server:
  port: 8080
spring:
 #profiles:
    #name: "ms-challenge-persons"
    #active: "local"
  devtools:
    add-properties: false

  jpa:
    hibernate:
      ddl-auto: "validate"
    databasePlatform: "org.hibernate.dialect.H2Dialect"
  datasource:
    url: "jdbc:postgresql://localhost:5432/person"
    username: "postgres"
    password: "person2023"
    driver-class-name: "org.postgresql.Driver"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true


