spring:
  application:
    name: "ms-challenge-person"
  devtools:
    restart:
      enabled: false
    add-properties: false
  jpa:
    hibernate:
      ddl-auto: "validate"
    databasePlatform: "org.hibernate.dialect.H2Dialect"
  datasource:
    url: "jdbc:postgresql://persondb.c8yfhn5lx6bh.us-east-1.rds.amazonaws.com:5432/person"
    username: "postgres"
    password: "xLxiho5v9Wy6"
    driver-class-name: "org.postgresql.Driver"

  r2dbc:
    enabled: true


